/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gifter } from "./Gifter";
export * as factories from "./factories";
export { Gifter__factory } from "./factories/Gifter__factory";
